$ = require 'jquery'
require 'script!foundation/js/foundation/foundation'
require 'script!foundation/js/foundation/foundation.abide'
require 'script!foundation/js/foundation/foundation.accordion'
require 'script!foundation/js/foundation/foundation.alert'
require 'script!foundation/js/foundation/foundation.clearing'
require 'script!foundation/js/foundation/foundation.dropdown'
require 'script!foundation/js/foundation/foundation.interchange'
require 'script!foundation/js/foundation/foundation.joyride'
require 'script!foundation/js/foundation/foundation.magellan'
require 'script!foundation/js/foundation/foundation.offcanvas'
require 'script!foundation/js/foundation/foundation.orbit'
require 'script!foundation/js/foundation/foundation.reveal'
require 'script!foundation/js/foundation/foundation.tab'
require 'script!foundation/js/foundation/foundation.tooltip'
require 'script!foundation/js/foundation/foundation.topbar'
require 'script!foundation/js/foundation/foundation.equalizer'

$(document).foundation()
